### ISSUE TITLE
Request for code review

### ISSUE THREAD

**Issue by hamid-murambiwa** [KDlamini/Catalog-of-My-Things#23]
[Project link](https://github.com/KDlamini/Catalog-of-My-Things/projects/1)
We have three members in our team.
Tasks for team member 1 is assigned to KDlamini.
Tasks for team member 2 is assigned to mbdesigns1989.
Tasks for team member 3 is assigned to hamid-murambiwa.

**Comment by ahmetbozaci** [comment]
Hi @KDlamini , @mbdesigns1989 , @hamid-murambiwa 

Your project is complete!
Everything is correct according to requirements.

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
